// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Implementation$Type } from "./Implementation";
import { TransparentProxy$Type } from "./TransparentProxy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Implementation"]: Implementation$Type;
    ["TransparentProxy"]: TransparentProxy$Type;
    ["contracts/upgrade/transparent.sol:Implementation"]: Implementation$Type;
    ["contracts/upgrade/transparent.sol:TransparentProxy"]: TransparentProxy$Type;
  }

  interface ContractTypesMap {
    ["Implementation"]: GetContractReturnType<Implementation$Type["abi"]>;
    ["TransparentProxy"]: GetContractReturnType<TransparentProxy$Type["abi"]>;
    ["contracts/upgrade/transparent.sol:Implementation"]: GetContractReturnType<Implementation$Type["abi"]>;
    ["contracts/upgrade/transparent.sol:TransparentProxy"]: GetContractReturnType<TransparentProxy$Type["abi"]>;
  }
}
