/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mintableErc20Sol from "./MintableERC20.sol";
export { MyToken__factory } from "./MyToken__factory";
