// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface AssemblyExample$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "AssemblyExample",
  "sourceName": "contracts/assemble/store.sol",
  "abi": [
    {
      "inputs": [],
      "name": "retrieve",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "x",
          "type": "uint256"
        }
      ],
      "name": "store",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "storeMemory",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "storedData",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x6080604052348015600f57600080fd5b506101c88061001f6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80632a1afcd9146100515780632e64cec11461006f5780636057361d1461008d578063f75e3ed8146100a9575b600080fd5b6100596100c7565b6040516100669190610119565b60405180910390f35b6100776100cd565b6040516100849190610119565b60405180910390f35b6100a760048036038101906100a29190610165565b6100dc565b005b6100b16100e3565b6040516100be9190610119565b60405180910390f35b60005481565b60008060005490508091505090565b8060005550565b600080604051602a81526020810160405280519150508091505090565b6000819050919050565b61011381610100565b82525050565b600060208201905061012e600083018461010a565b92915050565b600080fd5b61014281610100565b811461014d57600080fd5b50565b60008135905061015f81610139565b92915050565b60006020828403121561017b5761017a610134565b5b600061018984828501610150565b9150509291505056fea2646970667358221220843911d2bedb3c499bdde792c1c2245858a8d5cc93cce21e46a8f7c2aa9fcc3e64736f6c634300081c0033",
  "deployedBytecode": "0x608060405234801561001057600080fd5b506004361061004c5760003560e01c80632a1afcd9146100515780632e64cec11461006f5780636057361d1461008d578063f75e3ed8146100a9575b600080fd5b6100596100c7565b6040516100669190610119565b60405180910390f35b6100776100cd565b6040516100849190610119565b60405180910390f35b6100a760048036038101906100a29190610165565b6100dc565b005b6100b16100e3565b6040516100be9190610119565b60405180910390f35b60005481565b60008060005490508091505090565b8060005550565b600080604051602a81526020810160405280519150508091505090565b6000819050919050565b61011381610100565b82525050565b600060208201905061012e600083018461010a565b92915050565b600080fd5b61014281610100565b811461014d57600080fd5b50565b60008135905061015f81610139565b92915050565b60006020828403121561017b5761017a610134565b5b600061018984828501610150565b9150509291505056fea2646970667358221220843911d2bedb3c499bdde792c1c2245858a8d5cc93cce21e46a8f7c2aa9fcc3e64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "contracts/assemble/store.sol:AssemblyExample",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<AssemblyExample$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "contracts/assemble/store.sol:AssemblyExample",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<AssemblyExample$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "contracts/assemble/store.sol:AssemblyExample",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<AssemblyExample$Type["abi"]>>;
}
