// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Implementation$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Implementation",
  "sourceName": "contracts/upgrade/uups.sol",
  "abi": [
    {
      "inputs": [],
      "name": "getValue",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_value",
          "type": "uint256"
        }
      ],
      "name": "setValue",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_newImplementation",
          "type": "address"
        }
      ],
      "name": "upgrade",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "value",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x6080604052348015600f57600080fd5b506102348061001f6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630900f01014610051578063209652551461006d5780633fa4f2451461008b57806355241077146100a9575b600080fd5b61006b60048036038101906100669190610144565b6100c5565b005b6100756100c8565b604051610082919061018a565b60405180910390f35b6100936100d1565b6040516100a0919061018a565b60405180910390f35b6100c360048036038101906100be91906101d1565b6100d7565b005b50565b60008054905090565b60005481565b8060008190555050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000610111826100e6565b9050919050565b61012181610106565b811461012c57600080fd5b50565b60008135905061013e81610118565b92915050565b60006020828403121561015a576101596100e1565b5b60006101688482850161012f565b91505092915050565b6000819050919050565b61018481610171565b82525050565b600060208201905061019f600083018461017b565b92915050565b6101ae81610171565b81146101b957600080fd5b50565b6000813590506101cb816101a5565b92915050565b6000602082840312156101e7576101e66100e1565b5b60006101f5848285016101bc565b9150509291505056fea264697066735822122040054afb57355034bcb568228a405ddf1af95444e93e5c82b9e122f6a2a0dc4f64736f6c634300081c0033",
  "deployedBytecode": "0x608060405234801561001057600080fd5b506004361061004c5760003560e01c80630900f01014610051578063209652551461006d5780633fa4f2451461008b57806355241077146100a9575b600080fd5b61006b60048036038101906100669190610144565b6100c5565b005b6100756100c8565b604051610082919061018a565b60405180910390f35b6100936100d1565b6040516100a0919061018a565b60405180910390f35b6100c360048036038101906100be91906101d1565b6100d7565b005b50565b60008054905090565b60005481565b8060008190555050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000610111826100e6565b9050919050565b61012181610106565b811461012c57600080fd5b50565b60008135905061013e81610118565b92915050565b60006020828403121561015a576101596100e1565b5b60006101688482850161012f565b91505092915050565b6000819050919050565b61018481610171565b82525050565b600060208201905061019f600083018461017b565b92915050565b6101ae81610171565b81146101b957600080fd5b50565b6000813590506101cb816101a5565b92915050565b6000602082840312156101e7576101e66100e1565b5b60006101f5848285016101bc565b9150509291505056fea264697066735822122040054afb57355034bcb568228a405ddf1af95444e93e5c82b9e122f6a2a0dc4f64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "contracts/upgrade/uups.sol:Implementation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Implementation$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "contracts/upgrade/uups.sol:Implementation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Implementation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "contracts/upgrade/uups.sol:Implementation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Implementation$Type["abi"]>>;
}
