// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AssemblyExample$Type } from "./AssemblyExample";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AssemblyExample"]: AssemblyExample$Type;
    ["contracts/assemble/math.sol:AssemblyExample"]: AssemblyExample$Type;
  }

  interface ContractTypesMap {
    ["AssemblyExample"]: GetContractReturnType<AssemblyExample$Type["abi"]>;
    ["contracts/assemble/math.sol:AssemblyExample"]: GetContractReturnType<AssemblyExample$Type["abi"]>;
  }
}
