/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mintableErc20Sol from "./MintableERC20.sol";
export type { mintableErc20Sol };
export type { MyToken } from "./MyToken";
